name: Push Check

on:
  push:
    branches: [ main ]

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v2

      - name: "detekt"
        uses: natiginfo/action-detekt-all@1.23.1
        with:
          args: --fail-fast --config ./config/detekt/detekt.yml
