name: Push Check

on:
  push:
    branches: [ main ]

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v2

      - name: "setup java"
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: "run detekt"
        run: ./gradlew detekt
